# Witness inputs for sanctions_check circuit
sanctions_merkle_root = "0x1111"
identity_commitment = "0x2222"
compliance_nullifier = "0x3333"
credential_issuer_pubkey = "0x4444"
current_timestamp = "1700000000"
address_hash = "0xaaaa"
secret = "0xbbbb"
nullifier_secret = "0xcccc"
neighbor_leaf = "0xdddd"
neighbor_index = "1"
neighbor_path = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10"]
credential_hash = "0xeeee"
credential_secret = "0xffff"
credential_expiry = "1800000000"
