# Witness inputs for accredited_investor circuit
identity_commitment = "0x1111"
qualification_nullifier = "0x2222"
issuer_pubkey = "0x3333"
qualification_path = "0x4444"
current_timestamp = "1700000000"
address_hash = "0xaaaa"
secret = "0xbbbb"
nullifier_secret = "0xcccc"
attested_value = "1000000"
attestation_timestamp = "1700000000"
attestation_expiry = "1800000000"
attestation_secret = "0xdddd"
attestation_type = "1"
certification_id = "0xeeee"
certification_authority = "0xffff"
