# Witness inputs for encrypted_transfer circuit
sender_balance_commitment = "0x1111"
sender_new_balance_commitment = "0x2222"
recipient_balance_commitment = "0x3333"
recipient_new_balance_commitment = "0x4444"
transfer_amount_commitment = "0x5555"
nullifier = "0x6666"
min_transfer = "1"
max_transfer = "1000000"
sender_balance = "5000"
recipient_balance = "3000"
transfer_amount = "1000"
sender_randomness = "0xaaaa"
sender_new_randomness = "0xbbbb"
recipient_randomness = "0xcccc"
recipient_new_randomness = "0xdddd"
transfer_randomness = "0xeeee"
nullifier_secret = "0xffff"
sender = "0x1234"
nonce = "42"
