[package]
name = "compliance_proof"
type = "bin"
authors = ["Soul Protocol"]
description = "Privacy-preserving KYC/AML compliance verification"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
