# Witness inputs for balance_proof circuit
old_root = "0x1111"
new_root = "0x2222"
nullifier_hash = "0x3333"
public_amount = "1000"
token = "0x4444"
is_deposit = "1"
user_address = "0x5555"
old_balance = "5000"
new_balance = "6000"
nullifier_secret = "0xaaaa"
salt = "0xbbbb"
old_path_elements = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10", "0x11", "0x12", "0x13", "0x14"]
old_path_indices = ["0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0"]
new_path_elements = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10", "0x11", "0x12", "0x13", "0x14"]
new_path_indices = ["0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0"]
