[package]
name = "state_transfer"
type = "bin"
authors = ["Soul Protocol"]
description = "Optimized circuit for proving valid state ownership transfer"

[dependencies]
poseidon = { tag = "v0.2.3", git = "https://github.com/noir-lang/poseidon" }
