# Witness inputs for shielded_pool circuit
merkle_root = "0x1111"
nullifier = "0x2222"
recipient = "0x3333"
relayer = "0x4444"
fee = "100"
amount = "1000"
asset_id = "0x5555"
secret = "0xaaaa"
nullifier_preimage = "0xbbbb"
path_indices = ["0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1"]
siblings = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10", "0x11", "0x12", "0x13", "0x14", "0x15", "0x16", "0x17", "0x18", "0x19", "0x1a", "0x1b", "0x1c", "0x1d", "0x1e", "0x1f", "0x20"]
