# Witness inputs for cross_chain_proof circuit
source_proof_hash = "0x1111"
source_state_root = "0x2222"
source_block_number = "100"
source_chain_id = "1"
relayer_secret = "0xaaaa"
dest_chain_id = "42161"
relayer_pubkey = "0xbbbb"
proof_commitment = "0xcccc"
timestamp = "1700000000"
fee = "1000"
