# Witness inputs for policy circuit
policy_hash = "0x1111"
user_commitment = "0x2222"
merkle_root = "0x3333"
user_secret = "0xaaaa"
user_salt = "0xbbbb"
user_value = "5000"
policy_threshold = "1000"
policy_type = "1"
merkle_path_elements = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10", "0x11", "0x12", "0x13", "0x14"]
merkle_path_indices = ["0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0"]
