[package]
name = "gkr_sumcheck"
type = "lib"
authors = ["Soul Protocol"]
compiler_version = ">=0.33.0"
license = "MIT"
description = "GKR sumcheck protocol with Gruen's trick and optimizations based on Vitalik's tutorial"

[dependencies]
hekate_hash = { path = "../hekate_hash" }
