# Witness inputs for swap_proof circuit
old_balance_root = "0x1111"
new_balance_root = "0x2222"
pool_id = "0x3333"
nullifier_hash = "0x4444"
min_amount_out = "900"
fee_amount = "30"
reserve_in = "100000"
reserve_out = "100000"
new_reserve_in = "101000"
new_reserve_out = "99010"
pool_fee_rate = "30"
user_address = "0xaaaa"
token_in = "0xbbbb"
token_out = "0xcccc"
amount_in = "1000"
amount_out = "990"
nullifier_secret = "0xdddd"
salt = "0xeeee"
old_balance_in = "5000"
old_balance_out = "3000"
new_balance_in = "4000"
new_balance_out = "3990"
in_path_elements = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10", "0x11", "0x12", "0x13", "0x14"]
in_path_indices = ["0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0"]
out_path_elements = ["0x01", "0x02", "0x03", "0x04", "0x05", "0x06", "0x07", "0x08", "0x09", "0x0a", "0x0b", "0x0c", "0x0d", "0x0e", "0x0f", "0x10", "0x11", "0x12", "0x13", "0x14"]
out_path_indices = ["0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0", "0", "1", "0", "1", "0"]
